// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXMu9LD1uUeVlPqf-jvQlmK3WJ43esLE',
    appId: '1:123142457028:web:653caea6162c1c90862b91',
    messagingSenderId: '123142457028',
    projectId: 'net-scout',
    authDomain: 'net-scout.firebaseapp.com',
    storageBucket: 'net-scout.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7NUY6t5ev4iMieYyW3Tx1N3QWB3de5E',
    appId: '1:123142457028:android:bc30f9d536c5069e862b91',
    messagingSenderId: '123142457028',
    projectId: 'net-scout',
    storageBucket: 'net-scout.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPctAdcCEZoVheeMyf1kODgo7I2inSIlU',
    appId: '1:123142457028:ios:429392db4d62c9c9862b91',
    messagingSenderId: '123142457028',
    projectId: 'net-scout',
    storageBucket: 'net-scout.firebasestorage.app',
    iosBundleId: 'com.example.netScout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXMu9LD1uUeVlPqf-jvQlmK3WJ43esLE',
    appId: '1:123142457028:web:5dc58466b493ad44862b91',
    messagingSenderId: '123142457028',
    projectId: 'net-scout',
    authDomain: 'net-scout.firebaseapp.com',
    storageBucket: 'net-scout.firebasestorage.app',
  );
}
